name: Update NBA Injuries

# Run every 30 minutes
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:  # Allows manual run

jobs:
  scrape_injuries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium webdriver-manager unidecode

      - name: Run NBA Injuries Scraper
        run: |
          python nbainjuries.py

      - name: Commit & Push Updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add nba/data/nbaplayerstatus.csv
          git commit -m "Update NBA injuries CSV [skip ci]" || echo "No changes to commit"
          git push
